"""One-time authoring of the selected optional analysis topics; do not replay."""
from pathlib import Path
import json
from lxml import etree as ET
ROOT=Path(__file__).resolve().parents[1]
CH=ROOT/'source/chapters'
changes=json.loads((ROOT/'qa/additions/changed-source.json').read_text('utf-8'))
def add(chapter, filename, content):
    folder=next(CH.glob(chapter+'*'))
    p=folder/'sections'/filename
    assert not p.exists(), p
    ET.fromstring(content.encode())
    p.write_text(content.strip()+'\n',encoding='utf-8')
    cp=next(folder.glob('*.ptx'))
    old=cp.read_text('utf-8')
    cp.write_text(old.replace('</chapter>',f'  <xi:include href="sections/{filename}"/>\n\n</chapter>'),encoding='utf-8')
    changes.extend([str(p.relative_to(ROOT)),str(cp.relative_to(ROOT))])

add('ch15-', 'sec-additional-contraction-iteration.xml', r'''
<section xml:id="sec-additional-contraction-iteration">
  <title>Additional topics: contraction and fixed-point iteration</title>
  <introduction><p>A fixed-point equation can identify a possible limit, but the examples in <xref ref="sec-15-1-sequences"/> showed that this is not enough to prove convergence. A contraction supplies the missing control. This optional section uses the Cauchy criterion to prove existence, uniqueness, and usable error estimates.</p></introduction>
  <subsection xml:id="subsec-contraction-setting"><title>Distance, completeness, and contraction</title>
    <p>On a closed interval <m>D=[a,b]</m>, measure distance by <m>d(x,y)=|x-y|</m>. A map <m>T:D\to D</m> is a <em>contraction</em> if there is a constant <m>q</m>, with <m>0\le q&lt;1</m>, such that</p><p><me>d(Tx,Ty)\le q\,d(x,y)\qquad(x,y\in D).</me></p><p>The requirement <m>T(D)\subseteq D</m> keeps every iterate inside the set where the estimate holds. By the Mean Value Theorem, a differentiable map on the interval is a contraction if <m>|T'(x)|\le q&lt;1</m> throughout it.</p>
    <p>The same argument works for other kinds of objects. A <em>metric space</em> is a set <m>D</m> equipped with a distance <m>d</m> that is nonnegative, is zero exactly when its inputs are equal, satisfies <m>d(x,y)=d(y,x)</m>, and obeys the triangle inequality <m>d(x,z)\le d(x,y)+d(y,z)</m>. A sequence is Cauchy when <m>d(x_m,x_n)</m> becomes arbitrarily small for all sufficiently large <m>m,n</m>. The space is <em>complete</em> if every Cauchy sequence converges to an element of <m>D</m>. Closed real intervals are complete by <xref ref="thm-cauchy-sequences"/> and the preservation of inequalities under limits.</p>
  </subsection>
  <subsection xml:id="subsec-contraction-theorem"><title>The contraction theorem and its error estimates</title>
    <theorem xml:id="thm-contraction-iteration"><title>Contraction mapping theorem</title><statement><p>Let <m>D</m> be a nonempty complete metric space and let <m>T:D\to D</m> be a contraction with constant <m>q&lt;1</m>. There is exactly one fixed point <m>x_*\in D</m>. For every starting point <m>x_0\in D</m>, the iteration <m>x_{n+1}=T(x_n)</m> converges to <m>x_*</m>. For <m>n\ge1</m>,</p><p><md><mrow>d(x_n,x_*)\amp\le\frac{q^n}{1-q}\,d(x_1,x_0),</mrow><mrow>d(x_n,x_*)\amp\le\frac{q}{1-q}\,d(x_n,x_{n-1}),</mrow><mrow>d(x_n,x_*)\amp\le\frac{d(x_n,T(x_n))}{1-q}.</mrow></md></p></statement><proof><p>Repeated contraction gives <m>d(x_{k+1},x_k)\le q^k d(x_1,x_0)</m>. For <m>m&gt;n</m>, the triangle inequality and the finite geometric sum give</p><p><me>d(x_m,x_n)\le\sum_{k=n}^{m-1}q^k d(x_1,x_0)\le\frac{q^n}{1-q}d(x_1,x_0).</me></p><p>Thus the iterates are Cauchy and have a limit <m>x_*\in D</m>. The contraction inequality implies continuity of <m>T</m>, so taking the limit in <m>x_{n+1}=T(x_n)</m> gives <m>x_*=T(x_*)</m>. Two fixed points would satisfy <m>d(x_*,y_*)\le qd(x_*,y_*)</m>, forcing their distance to be zero.</p><p>Letting <m>m\to\infty</m> in the finite-tail bound proves the first estimate. Starting the same geometric bound at the most recent step proves the second. For any <m>x\in D</m>,</p><p><me>d(x,x_*)\le d(x,Tx)+d(Tx,Tx_*)\le d(x,Tx)+q\,d(x,x_*).</me></p><p>Rearranging proves the residual estimate, including the third bound. If <m>q=0</m>, the map is constant and one step already reaches its fixed point.</p></proof></theorem>
    <p>The first bound is an <em>a priori</em> estimate: it can predict an iteration count from the initial step. The second is an <em>a posteriori</em> estimate: it uses the step just computed. In exact arithmetic, stop with an error at most <m>\varepsilon</m> when <m>q|x_n-x_{n-1}|/(1-q)\le\varepsilon</m>. A small step alone is not the bound; the factor <m>q/(1-q)</m> matters, especially when <m>q</m> is near one.</p>
    <p>If an implementation produces approximate steps <m>\widetilde x_{n+1}</m> with <m>d(\widetilde x_{n+1},T\widetilde x_n)\le\delta</m>, while keeping them in <m>D</m>, then</p><p><me>d(\widetilde x_n,x_*)\le q^n d(\widetilde x_0,x_*)+\frac{\delta(1-q^n)}{1-q}.</me></p><p>This follows by iterating <m>e_{n+1}\le qe_n+\delta</m>. It explains the error floor caused by inaccurate function evaluations or rounding. A certified residual bound must include those evaluation errors.</p>
  </subsection>
  <subsection xml:id="subsec-contraction-examples"><title>Choosing a useful iteration</title>
    <example xml:id="ex-cos-contraction"><title>Solving <m>x=\cos x</m></title><p>The map <m>T(x)=\cos x</m> sends <m>[0,1]</m> into itself. On that interval, <m>|T'(x)|=\sin x\le\sin1&lt;0.85</m>, so take <m>q=0.85</m>. Starting at <m>x_0=1</m> gives <m>x_1\approx0.540302</m>, <m>x_2\approx0.857553</m>, and eventually <m>x_*\approx0.739085</m>. The theorem proves convergence for every start in the interval, even though the iterates need not be monotone. The residual estimate bounds the distance to the root by <m>|x-\cos x|/0.15</m>.</p></example>
    <figure xml:id="fig-contraction-cos-cobweb"><caption>Vertical moves to <m>y=\cos x</m> followed by horizontal moves to <m>y=x</m> produce the contraction iteration. The steps alternate around the fixed point.</caption><image width="65%"><description><p>The cosine graph and diagonal on the unit square, with the first four cobweb steps starting at x equal to one.</p></description><latex-image>
\begin{tikzpicture}
\begin{axis}[width=0.65\textwidth,height=0.52\textwidth,xmin=0,xmax=1.08,ymin=0,ymax=1.08,axis lines=left,xlabel={$x$},ylabel={$y$},xtick={0,0.5,1},ytick={0,0.5,1},legend style={draw=none,at={(0.05,0.95)},anchor=north west}]
\addplot[thick,domain=0:1,samples=100]{cos(deg(x))};\addlegendentry{$y=\cos x$}
\addplot[dashed,domain=0:1]{x};\addlegendentry{$y=x$}
\addplot[blue] coordinates {(1,0)(1,0.540302)(0.540302,0.540302)(0.540302,0.857553)(0.857553,0.857553)(0.857553,0.654290)(0.654290,0.654290)(0.654290,0.793480)(0.793480,0.793480)};
\end{axis}
\end{tikzpicture}
    </latex-image></image></figure>
    <warning xml:id="warn-contraction-hypotheses"><title>Why the set and the constant matter</title><p>The contraction <m>T(x)=x/2</m> on the open interval <m>(0,1)</m> has no fixed point there: its iterates tend to zero outside the set. Completeness prevents this escape. On <m>[0,1]</m>, the map <m>T(x)=1-x</m> has a fixed point but contraction constant only <m>1</m>; most iterates oscillate. Neither hypothesis can simply be discarded.</p></warning>
    <exercise xml:id="exr-contraction-error"><title>Prove convergence and choose a stopping rule</title><statement><p>For <m>T(x)=(x+2)/3</m> on <m>[0,2]</m>, prove the self-map and contraction properties, identify the fixed point, and find an a priori iteration count guaranteeing error at most <m>10^{-6}</m> when <m>x_0=0</m>. Express an a posteriori stopping test.</p></statement><hint><p>Use <m>q=1/3</m>, <m>x_*=1</m>, and <m>|x_1-x_0|=2/3</m>. The first bound is <m>3^{-n}</m>, so <m>n=13</m> suffices. Stop when <m>|x_n-x_{n-1}|/2\le10^{-6}</m>.</p></hint></exercise>
  </subsection>
</section>
''')

add('ch16-', 'sec-additional-weierstrass-m-test.xml', r'''
<section xml:id="sec-additional-weierstrass-m-test">
  <title>Additional topics: the Weierstrass M-test</title>
  <introduction><p>In <xref ref="sec-16-8-uniform-convergence-preview"/>, a single bound independent of <m>x</m> controlled a whole interval. The M-test extends that idea from power series to arbitrary series of functions. This optional section uses the Cauchy criterion from Chapter <xref ref="ch15-sequences-and-infinite-series"/>.</p></introduction>
  <subsection xml:id="subsec-m-test-theorem"><title>A numerical majorant controls a function series</title>
    <p>For functions <m>f_n:D\to\mathbb R</m>, the series <m>\sum_{n=1}^\infty f_n(x)</m> converges uniformly to <m>F</m> on <m>D</m> when its partial sums <m>S_N(x)</m> satisfy: for every <m>\varepsilon&gt;0</m>, there is one <m>N_0</m> such that <m>|F(x)-S_N(x)|&lt;\varepsilon</m> for all <m>N\ge N_0</m> and every <m>x\in D</m>.</p>
    <theorem xml:id="thm-weierstrass-m-test"><title>Weierstrass M-test</title><statement><p>Suppose <m>|f_n(x)|\le M_n</m> for every <m>x\in D</m>, where <m>M_n\ge0</m> and <m>\sum M_n</m> converges. Then <m>\sum f_n(x)</m> converges absolutely at every point and uniformly on <m>D</m>. Its remainder satisfies</p><p><me>|F(x)-S_N(x)|\le\sum_{n=N+1}^\infty M_n\qquad(x\in D).</me></p></statement><proof><p>Absolute convergence at each point follows by numerical comparison. For every <m>q\ge p</m>,</p><p><me>\left|\sum_{n=p}^q f_n(x)\right|\le\sum_{n=p}^q M_n.</me></p><p>The Cauchy criterion makes the right side arbitrarily small for sufficiently large <m>p</m>, independently of <m>q</m> and <m>x</m>. Letting <m>q\to\infty</m> yields the remainder bound. The tails of the convergent majorant series tend to zero, so this same bound proves uniform convergence.</p></proof></theorem>
    <p>If each <m>f_n</m> is continuous, the uniform-limit theorem makes <m>F</m> continuous. On a finite closed interval, the integration theorem in <xref ref="sec-16-8-uniform-convergence-preview"/> then gives <m>\int_a^b F=\sum_{n=1}^\infty\int_a^b f_n</m>. To differentiate term by term, one needs additional control of the derivative series; the M-test for the original terms alone is insufficient.</p>
  </subsection>
  <subsection xml:id="subsec-m-test-examples"><title>Examples, error bounds, and limitations</title>
    <example xml:id="ex-m-test-sine"><title>A uniformly convergent trigonometric series</title><p>For every real <m>x</m>, <m>|\sin(nx)/n^2|\le1/n^2</m>. Since <m>\sum1/n^2</m> converges, the function</p><p><me>F(x)=\sum_{n=1}^\infty\frac{\sin(nx)}{n^2}</me></p><p>is continuous, and the integral-test tail bound gives <m>|F(x)-S_N(x)|\le1/N</m> for every real <m>x</m>. On any <m>[0,b]</m>, term-by-term integration is valid and yields <m>\int_0^bF(x)\,dx=\sum_{n=1}^\infty(1-\cos(nb))/n^3</m>. This conclusion uses no Fourier-series theorem.</p></example>
    <example xml:id="ex-m-test-power"><title>The power-series safety margin revisited</title><p>If <m>\sum c_n(x-a)^n</m> has radius <m>R&gt;0</m>, fix <m>0&lt;r&lt;R</m>. On <m>|x-a|\le r</m>, take <m>M_n=|c_n|r^n</m>. This numerical series converges because <m>r</m> lies inside the radius. The M-test proves uniform convergence on that smaller interval. An endpoint at distance <m>R</m> requires its own analysis.</p></example>
    <warning xml:id="warn-m-test-derivatives"><title>Uniform convergence does not control every operation</title><p>The series <m>\sum_{n=1}^\infty\sin(n^2x)/n^2</m> passes the M-test on <m>\mathbb R</m>. But its formally differentiated series is <m>\sum\cos(n^2x)</m>, which diverges at <m>x=0</m> because its terms equal <m>1</m>. The original M-test does not justify that differentiation.</p></warning>
    <p>The M-test is sufficient, not necessary. A function series with constant terms <m>f_n(x)=(-1)^{n-1}/n</m> converges uniformly on any set, because the alternating-series remainder is at most <m>1/(N+1)</m> independently of <m>x</m>. But any nonnegative majorant <m>M_n</m> must be at least <m>1/n</m>, so no convergent majorant exists.</p>
    <exercise xml:id="exr-m-test"><title>Find the domain-wide bound</title><statement><p>Prove uniform convergence of <m>\sum_{n=1}^\infty x^n/n^2</m> on <m>[-1,1]</m> and give a remainder bound. Then show that <m>\sum_{n=0}^\infty(1-x)x^n</m> converges pointwise on <m>[0,1]</m> but not uniformly.</p></statement><hint><p>Use <m>M_n=1/n^2</m> and remainder at most <m>1/N</m>. The second sum equals <m>1</m> for <m>x&lt;1</m> and <m>0</m> at <m>x=1</m>. Its continuous partial sums cannot converge uniformly to this discontinuous limit; alternatively, their error for <m>x&lt;1</m> is <m>x^{N+1}</m>, whose supremum is <m>1</m>.</p></hint></exercise>
  </subsection>
</section>
''')

add('ch17-', 'sec-additional-local-existence-uniqueness.xml', r'''
<section xml:id="sec-additional-local-existence-uniqueness">
  <title>Additional topics: local existence and uniqueness</title>
  <introduction><p>Chapter <xref ref="ch13-differential-equations-laws-written-as-derivatives"/> used initial conditions to select solutions, but this selection requires hypotheses on the slope law. We can now give a precise theorem and prove it using completeness, uniform convergence, and the contraction theorem. This optional section can be read independently of the complex-number and Fourier material in this chapter.</p></introduction>
  <subsection xml:id="subsec-lipschitz-ode"><title>A Lipschitz condition in the dependent variable</title>
    <p>Consider <m>y'=F(t,y)</m>, <m>y(t_0)=y_0</m>. Fix positive <m>a,b</m> and the rectangle</p><p><me>R=\{(t,y):|t-t_0|\le a,\ |y-y_0|\le b\}.</me></p><p>The law is <em>Lipschitz in <m>y</m> on <m>R</m></em> if one constant <m>L\ge0</m> satisfies</p><p><me>|F(t,u)-F(t,v)|\le L|u-v|</me></p><p>whenever <m>(t,u),(t,v)\in R</m>. The same <m>L</m> must work for every time in the rectangle. A bound <m>|\partial F/\partial y|\le L</m> suffices: this derivative means differentiating with respect to <m>y</m> while holding <m>t</m> fixed, and the one-variable Mean Value Theorem applies. Lipschitz continuity does not require that derivative to exist; <m>F(t,y)=|y|</m> is Lipschitz with <m>L=1</m>.</p>
    <theorem xml:id="thm-local-picard-lindelof"><title>A local existence and uniqueness theorem</title><statement><p>Suppose <m>F</m> is continuous on <m>R</m>, satisfies the Lipschitz condition above, and <m>|F(t,y)|\le M</m> on <m>R</m>. Choose <m>h&gt;0</m> so that</p><p><me>h\le a,\qquad hM\le b,\qquad hL&lt;1.</me></p><p>Then there is a continuously differentiable solution on <m>I=[t_0-h,t_0+h]</m> with <m>y(t_0)=y_0</m> and <m>|y(t)-y_0|\le b</m>. It is unique among solutions on <m>I</m> whose graphs stay in <m>R</m>. In particular, the initial value problem has a unique local solution near <m>t_0</m>.</p></statement></theorem>
    <p>Continuity on the closed rectangle supplies a finite bound <m>M</m>. There is always a positive admissible <m>h</m>; for example, <m>h=\min\{a,b/(M+1),1/(2(L+1))\}</m> works, including when <m>M=0</m> or <m>L=0</m>. The theorem provides a guaranteed local interval, which need not be the largest possible interval.</p>
  </subsection>
  <subsection xml:id="subsec-picard-proof"><title>Proof by successive approximations</title>
    <p>Integrating the differential equation gives the equivalent integral equation</p><p><me>y(t)=y_0+\int_{t_0}^t F(s,y(s))\,ds.</me></p><p>Let <m>D</m> consist of continuous functions <m>u:I\to\mathbb R</m> satisfying <m>|u(t)-y_0|\le b</m>. Measure distance by the <em>uniform distance</em></p><p><me>d(u,v)=\max_{t\in I}|u(t)-v(t)|.</me></p><p>This is a metric, and <m>D</m> is complete. Indeed, a Cauchy sequence in this metric is Cauchy at each point, hence has a pointwise real limit by <xref ref="thm-cauchy-sequences"/>. Taking the limit in the uniform Cauchy bound shows uniform convergence to that function. The uniform-limit theorem preserves continuity, and taking pointwise limits preserves <m>|u(t)-y_0|\le b</m>. Thus the limit belongs to <m>D</m>.</p>
    <p>Define the Picard map</p><p><me>(Tu)(t)=y_0+\int_{t_0}^t F(s,u(s))\,ds.</me></p><p>Continuity of <m>F</m> and <m>u</m> makes <m>Tu</m> continuous, and</p><p><me>|(Tu)(t)-y_0|\le M|t-t_0|\le Mh\le b.</me></p><p>So <m>T</m> maps <m>D</m> into itself. Moreover,</p><p><me>|(Tu)(t)-(Tv)(t)|\le L|t-t_0|\,d(u,v)\le Lh\,d(u,v).</me></p><p>The contraction constant is <m>q=Lh&lt;1</m>. By <xref ref="thm-contraction-iteration"/>, <m>T</m> has a unique fixed point <m>y</m> in <m>D</m>. The Fundamental Theorem of Calculus shows that this fixed point is continuously differentiable and solves the differential equation. Conversely, every solution with graph in <m>R</m> satisfies the integral equation, so uniqueness of the fixed point proves the stated uniqueness. Any other local solution is close to <m>y_0</m> by continuity and hence stays in <m>R</m> on a sufficiently small interval; the same contraction argument on that interval shows that the two local solutions agree there.</p>
    <p>Starting with <m>u_0(t)=y_0</m>, successive approximations <m>u_{n+1}=Tu_n</m> converge uniformly, with the explicit bound</p><p><me>d(u_n,y)\le\frac{q^n}{1-q}\,Mh\qquad(n\ge1).</me></p>
    <example xml:id="ex-picard-exponential"><title>Picard iterates for exponential growth</title><p>For <m>y'=y</m>, <m>y(0)=1</m>, take <m>a=1</m>, <m>b=1</m>, <m>M=2</m>, <m>L=1</m>, and <m>h=1/2</m>. The iterates are <m>u_0=1</m>, <m>u_1=1+t</m>, <m>u_2=1+t+t^2/2</m>, and in general <m>u_n=\sum_{k=0}^n t^k/k!</m>. Their uniform limit is <m>e^t</m>. Picard iteration integrates an entire previous function; Euler and Runge–Kutta methods instead advance numerical values along a grid.</p></example>
  </subsection>
  <subsection xml:id="subsec-ode-counterexamples"><title>What the hypotheses do and do not guarantee</title>
    <example xml:id="ex-ode-nonunique-waiting"><title>Continuity alone does not guarantee uniqueness</title><p>The law <m>F(t,y)=2\sqrt{|y|}</m> is continuous but not Lipschitz near <m>y=0</m>, since <m>|F(t,u)-F(t,0)|/|u|=2/\sqrt u</m> for <m>u&gt;0</m>. For the initial data <m>y(0)=0</m>, the zero solution and every function</p><p><me>y_c(t)=\begin{cases}0,\amp t\le c,\\(t-c)^2,\amp t&gt;c,\end{cases}\qquad c\ge0,</me></p><p>solve the equation. At <m>t=c</m>, both one-sided derivatives are zero, so these are actual differentiable solutions. The solution may wait and then depart. Initial data alone do not force uniqueness.</p></example>
    <figure xml:id="fig-ode-nonunique-waiting"><caption>Three solutions of <m>y'=2\sqrt{|y|}</m> pass through <m>(0,0)</m>: immediate departure, departure after time one, and the zero solution.</caption><image width="70%"><description><p>On the interval from minus one to two, a parabola beginning at time zero, a parabola beginning at time one, and the zero solution all coincide initially on the horizontal axis.</p></description><latex-image>
\begin{tikzpicture}
\begin{axis}[width=0.72\textwidth,height=0.43\textwidth,xmin=-1,xmax=2.1,ymin=-0.2,ymax=4.4,axis lines=middle,xlabel={$t$},ylabel={$y$},xtick={-1,0,1,2},ytick={0,1,2,3,4},legend style={draw=none,at={(0.03,0.97)},anchor=north west}]
\addplot[thick,domain=-1:2,samples=120]{max(x,0)^2};\addlegendentry{$c=0$}
\addplot[thick,dashed,domain=-1:2,samples=120]{max(x-1,0)^2};\addlegendentry{$c=1$}
\addplot[dotted,very thick,domain=-1:2]{0};\addlegendentry{$y=0$}
\end{axis}
\end{tikzpicture}
    </latex-image></image></figure>
    <example xml:id="ex-ode-no-existence-discontinuous"><title>Without continuity, existence can fail</title><p>Define <m>F(y)=1</m> if <m>y=0</m> and <m>F(y)=0</m> otherwise. There is no differentiable solution of <m>y'=F(y)</m> with <m>y(0)=0</m> on a neighborhood of zero. A solution would have <m>y'(0)=1</m>, hence <m>y(t)&gt;0</m> for all sufficiently small positive <m>t</m>. There its derivative would be zero, forcing it to be constant by the Mean Value Theorem. Continuity at zero would make that constant zero, a contradiction.</p></example>
    <p>Lipschitz continuity is sufficient for uniqueness, but not necessary. For <m>y'=-\sqrt[3]{y}</m>, <m>y(0)=0</m>, the law is not Lipschitz at zero, yet the zero solution is the only forward solution. Along any differentiable solution, <m>(y^2)'=-2|y|^{4/3}\le0</m>. Starting from <m>y^2=0</m>, nonnegativity forces <m>y=0</m> for future times. This statement concerns forward uniqueness; backward departure is possible.</p>
    <warning xml:id="warn-ode-local-not-global"><title>Local does not mean global</title><p>The smooth law <m>y'=y^2</m>, <m>y(0)=1</m>, has the unique solution <m>y=1/(1-t)</m> near zero, but the solution becomes unbounded at time one. Local existence and uniqueness do not imply that a solution continues for all time.</p></warning>
    <exercise xml:id="exr-local-ode"><title>Find a guaranteed interval</title><statement><p>Apply the theorem to <m>y'=t+y^2</m>, <m>y(0)=1</m>, on <m>|t|\le1</m>, <m>|y-1|\le1</m>. Find valid <m>M,L,h</m>. Then verify the waiting solutions in the nonuniqueness example at the joining point.</p></statement><hint><p>Here <m>0\le y\le2</m>, so <m>M=5</m> and <m>L=4</m> work. Choose <m>h=1/5</m>: <m>hM=1</m> and <m>hL=4/5&lt;1</m>. At the joining point, <m>y_c'=0=2\sqrt{|y_c|}</m>.</p></hint></exercise>
  </subsection>
</section>
''')
(ROOT/'qa/additions/changed-source.json').write_text(json.dumps(sorted(set(changes)),indent=2),encoding='utf-8')
print('Added three optional analysis sections.')
