from pathlib import Path
import re
from audit_edit import ROOT,save,record
fixes={
'checkpoint-1-4-two-directions-before-limits':r'Finite differences and finite sums undo each other exactly, with a starting position supplied. They give interval changes and average rates, rather than an instantaneous rate. Multiplying a sampled instantaneous velocity by a finite step is generally only an estimate when velocity varies within the step.',
'checkpoint-3-2-direct-substitution':r'For the polynomial and rational functions considered here, substitution gives the limit when the denominator is nonzero. In general, substitution is justified by continuity at the approach point. The form <m>\frac00</m> says only that direct substitution failed; factoring, rationalizing, or another method must reveal the nearby behavior.',
'checkpoint-3-5-continuity-three-conditions':r'Check separately that the function value exists, that the nearby values have a limit, and that the value equals that limit. A hole removes the function value; relocating a point can leave the limit unchanged while breaking agreement with the value.',
'checkpoint-3-9-decision-guide':r'First check whether continuity justifies direct substitution. The form <m>\frac00</m> is a question. Different one-sided limits block a two-sided limit. Growth without bound is infinite behavior, not a real-number target.',
'checkpoint-5-3-both-links':r'The chain rule guarantees a derivative when both links are differentiable at the required points. If either hypothesis fails, the rule gives no conclusion; the composite may still be differentiable. For example, <m>|x|^2=x^2</m> is differentiable at zero although the inner function <m>|x|</m> is not.',
'checkpoint-5-8-no-minus-for-hyperbolic':r'Hyperbolic sine is the odd difference of <m>e^x</m> and <m>e^{-x}</m>, while hyperbolic cosine is their even sum. The chain-rule minus sign in the derivative of <m>e^{-x}</m> changes the difference into the sum and the sum into the difference.',
'checkpoint-6-1-sign-chart':r'Find zeros and points where <m>f\prime</m> is undefined, then establish the sign on each remaining interval. For the continuous derivative formulas used in these sketches, the Intermediate Value Theorem ensures that the sign cannot switch without passing through zero.',
'checkpoint-6-4-second-derivative-test':r'When <m>f\prime(c)=0</m> and <m>f\prime\prime(c)&gt;0</m>, the definition of the derivative of <m>f\prime</m> forces <m>f\prime</m> negative just to the left and positive just to the right. Reverse the signs for <m>f\prime\prime(c)&lt;0</m>. When the second derivative is zero, a minimum, maximum, or neither is possible.',
'checkpoint-6-6-derivatives-reveal-ratio':r'If <m>f(a)=g(a)=0</m> and <m>g\prime(a)\ne0</m>, the local linear models have the common factor <m>x-a</m>, leaving the ratio of slopes. This explains the simplest case; l’Hospital’s Rule handles other cases under its stated hypotheses.',
'checkpoint-6-6-when-lhospital-fails':r'Check the indeterminate form, differentiability, and the nonvanishing denominator derivative on the punctured interval. Under the theorem’s hypotheses, a limit of the derivative quotient gives a limit of the original quotient. The converse is not promised.',
'checkpoint-8-1-rectangle-as-displacement':r'Signed displacement equals constant velocity times elapsed time. Distance traveled equals speed times elapsed time. On the graph, height times width is the corresponding product.',
'checkpoint-8-4-integrability-is-strong':r'Integrability requires all sufficiently fine Riemann sums to approach one value. For the function that is one on rationals and zero on irrationals, every subinterval allows either sample height, so the sums can stay a full interval length apart.',
'checkpoint-8-5-net-versus-total':r'Cancellation is removed when we integrate the absolute value. Write the positive and negative accumulated amounts as <m>P</m> and <m>N</m>. Then the total is <m>P+N</m> and the absolute net is <m>|P-N|</m>; the inequality is strict precisely when both amounts are positive.',
'checkpoint-9-2-ftc-undo':r'Think of <m>A(x)</m> as a position record built from a continuous velocity record <m>f</m>. Its rate of change is the current velocity. An odometer instead records total distance and therefore accumulates speed.',
'checkpoint-10-4-my-mx':r'The signed coordinate measured from the <m>y</m>-axis is <m>x</m>, while the signed coordinate measured from the <m>x</m>-axis is <m>y</m>. Ordinary distance would use absolute values, but moments retain the side of the axis.',
'checkpoint-11-2-odd-even':r'If a sine or cosine power is odd, saving one factor leaves an even power of that same function, which the Pythagorean identity converts into the other function. If both powers are even, half-angle identities lower the powers instead.',
'checkpoint-11-4-linear-factors':r'A linear denominator has a nonzero constant derivative. Substituting that linear expression as <m>u</m> turns its reciprocal into a constant multiple of <m>1/u</m>, whose antiderivative is <m>\ln|u|</m>.',
'checkpoint-11-8-jump-across':r'First check the Fundamental Theorem’s hypotheses; continuity on the whole interval is sufficient. At a blow-up, split the integral and replace each dangerous endpoint by a separate limit. If either side diverges, the improper integral diverges.',
'checkpoint-12-5-simple-versus-multiple':r'Quadratic convergence near a simple root uses a nonzero derivative there. At a root of finite multiplicity <m>m&gt;1</m>, ordinary Newton iteration usually has only linear convergence, with leading error factor <m>(m-1)/m</m>. Such a root can touch or cross the axis.',
'checkpoint-12-7-integration-versus-differentiation':r'Averaging can reduce noise. Subtracting nearly equal values and dividing by a small step magnifies roundoff and measurement noise. For a sufficiently smooth function, shrinking the step reduces truncation error, so these competing errors require a balance.',
'checkpoint-13-6-outside-input':r'The integrating-factor formula accumulates the input term. If the input is identically zero, the equation is homogeneous and only the initial value is propagated by the homogeneous solution.',
'checkpoint-14-2-slope-as-ratio':r'When <m>x\prime(t)\ne0</m>, divide the coordinate rates to obtain <m>dy/dx</m>. If <m>x\prime(t)=0</m> and <m>y\prime(t)\ne0</m>, the tangent is vertical. If both vanish, the quotient alone cannot decide whether the curve is a graph or has a tangent.',
'checkpoint-14-2-motion-as-pairs':r'Each position coordinate is an ordinary function of time. Their derivatives form the velocity pair, which points in the direction of motion when nonzero; its length is the speed.',
'checkpoint-14-4-distance-and-angle':r'Polar coordinates use an angle from the positive <m>x</m>-axis and a signed radial coordinate. The distance from the origin is <m>|r|</m>; for <m>r\ge0</m>, it is <m>r</m> itself.',
'checkpoint-14-6-focus-directrix':r'For a nondegenerate focus-directrix conic, the positive ratio is <m>e</m>. The cases <m>0&lt;e&lt;1</m>, <m>e=1</m>, and <m>e&gt;1</m> give ellipse, parabola, and hyperbola. A circle is the limiting case of an ellipse as eccentricity tends to zero.',
'checkpoint-14-6-polar-one-equation':r'Polar coordinates measure distance from the focus directly when <m>r\ge0</m>. In the standard focus form, after normalizing the constant denominator term to one, the absolute value of the cosine or sine coefficient is the eccentricity.',
'checkpoint-14-10-plane-as-numbers':r'The plane can be a pair of coordinates, a polar pair, or one complex number. The exponential series gives the proof of Euler’s formula developed later in the book.',
'checkpoint-15-1-what-convergence-means':r'Convergence is a promise about every required closeness, not a snapshot of a few terms. Persistent oscillation between separated values and unbounded growth prevent convergence; oscillation with shrinking amplitude can still converge.',
'checkpoint-15-1-monotone-bounded':r'An increasing sequence with no ceiling grows without bound. Boundedness alone is not enough: a sequence alternating between two distinct values does not converge. Completeness supplies the least upper bound approached by an increasing bounded sequence.',
'checkpoint-15-2-geometric-ratio':r'For a nonzero first term, the finite-sum formula contains a leftover power of the ratio. It vanishes when <m>|r|&lt;1</m>. When <m>|r|\ge1</m>, the terms do not tend to zero. If the first term is zero, every term and every partial sum is zero for any ratio.',
'checkpoint-15-5-next-term-error':r'Odd and even partial sums bound the limit, and the gap between consecutive bounds is the magnitude of the next term. Ending with a positive term gives an upper bound; ending with a negative term gives a lower bound. Equality is possible.',
'checkpoint-15-8-ratio-silent':r'A ratio limit of one supplies no geometric decay bound with a fixed ratio less than one. Both convergent and divergent series can have that limit; try another test.',
'checkpoint-15-9-absolute-rearrangement':r'Absolute convergence means the total magnitude of all terms is finite, so a sufficiently late tail is small regardless of order. Conditional convergence has infinite positive and negative totals, so order can steer their balance.',
'checkpoint-16-5-two-error-languages':r'The Lagrange form gives a derivative-based worst-case bound. The integral form expresses the remainder as accumulated derivative information. Under the alternating-series hypotheses, the first omitted term supplies an error bound rather than necessarily the exact error.',
'checkpoint-16-6-binomial-as-taylor':r'The coefficients come from the derivatives of <m>(1+x)^p</m> at zero. For a nonnegative integer <m>p</m>, the series terminates and is a polynomial valid everywhere. Otherwise the power series has radius one, and its endpoints require separate checks.',
'checkpoint-16-9-local-becomes-bad':r'A Taylor polynomial is built from data at one center, but being a polynomial it is defined everywhere. Its accuracy away from that center needs a remainder estimate. The associated infinite Taylor series has its own convergence radius and need not represent the function beyond it.',
'checkpoint-16-10-series-hide-rotation':r'Cosine and sine are respectively the even and odd parts of the exponential series after the imaginary substitution that cycles the signs. The next chapter turns that cycle into rotation in the plane.',
'checkpoint-17-5-local-divergence':r'A continuous integrand whose integral vanishes on every interval must be zero: a nonzero value would retain its sign on a small interval. The term <m>q_x</m> measures how flux changes along the line, the one-dimensional divergence.',
}
# Locate each exercise by ID and alter only its hint, preserving the surrounding XML.
for eid,fragment in fixes.items():
 matches=[]
 for p in (ROOT/'source').rglob('*.xml'):
  s=p.read_text('utf-8')
  m=re.search(r'<exercise\s+xml:id="'+re.escape(eid)+r'">[\s\S]*?</exercise>',s)
  if m: matches.append((p,s,m))
 if len(matches)!=1: raise ValueError((eid,len(matches)))
 p,s,m=matches[0]; old=m.group();new=re.sub(r'<hint>[\s\S]*?</hint>',lambda _: '<hint><p>'+fragment+'</p></hint>',old,count=1)
 if old==new: continue
 save(p,s[:m.start()]+new+s[m.end():]);record(p,'Correct exercise hint: '+eid,old,new)
