from audit_edit import replace,ROOT,save,record

def c(n,s):return f'chapters/ch{n:02}*/sections/sec-{n}-{s}-*.xml'
replace(c(5,8),'This is not a polynomial.  The exponent is not an integer.  But logarithms turn powers into products.',r'This is not a polynomial. The exponent is not an integer. For <m>x&gt;0</m>, define a real power by <m>x^r=e^{r\ln x}</m>. The chain rule already shows that this function is differentiable. Logarithms then turn powers into products.','Define real powers without assuming their differentiability in the proof')
replace(c(5,4),'The negative sign says that the upper half of the circle is concave down at <m>(3,4)</m>.','The negative sign says that the tangent slopes are decreasing near <m>(3,4)</m>, a shape called <em>concave down</em>. Chapter 6 develops this terminology.','Explain concavity at its first use')
replace(c(4,7),'meters, measured from a chosen origin on the track.',r'meters for <m>t\ge0</m>, measured from a chosen origin on the track.','State the forward-time domain of the introductory speeding-up example')
replace(c(7,3),'So far we have mostly used the first and third.',r'The input-change estimate requires <m>f\prime(x)\ne0</m>. So far we have mostly used the first and third.','Exclude division by a zero sensitivity')
replace(c(7,5),'The differential equation',r'Assume the initial amount <m>y_0&gt;0</m> in growth, decay, doubling-time, and half-life models. The differential equation','Positive amounts are required for the relative growth and doubling interpretations')
replace(c(7,7),'Suppose the upper medium has speed <m>v_1</m>, and the lower medium has speed <m>v_2</m>.',r'Suppose the upper medium has speed <m>v_1&gt;0</m>, and the lower medium has speed <m>v_2&gt;0</m>.','Travel time divides by positive speeds')
replace(c(12,6),'The following language-neutral pseudocode gives the structure.',r'The following language-neutral pseudocode gives the structure. Supply a function defined throughout <m>[a,b]</m>, with <m>a&lt;b</m> and a positive integer subdivision count <m>n</m>. Simpson’s Rule also requires even <m>n</m>.','Specify quadrature algorithm input requirements')
p=next((ROOT/'source').glob(c(12,6)));s=p.read_text('utf-8');old=s
for name in ('midpoint','trapezoid','simpson'):
 s=s.replace(f'function {name}(f, a, b, n):\n',f'function {name}(f, a, b, n):\n    if n is not a positive integer or a &gt;= b:\n        stop with message "Require positive integer n and a less than b"\n')
save(p,s);record(p,'Reject invalid quadrature subdivision counts and intervals',old,s)
replace(c(14,10),'and square carefully.',r'and square carefully. This step initially assumes <m>r\ge0</m>; retain the condition <m>p-ex\ge0</m> to avoid adding a branch by squaring. For <m>e&gt;1</m>, allowing signed negative <m>r</m> in the original polar equation supplies the other hyperbola branch.','Track the radial sign and branch added by squaring')
replace(c(17,6),'The function <m>L</m> is called a <em>Lagrangian</em>.',r'Here <m>\partial L/\partial y</m> means differentiate with respect to the second argument while holding the other arguments fixed; <m>\partial L/\partial y\prime</m> means differentiate with respect to the third argument, the slope. Assume <m>L</m> is twice continuously differentiable on the relevant domain. The function <m>L</m> is called a <em>Lagrangian</em>.','Define the partial derivative notation and regularity in the Euler-Lagrange preview')
replace(c(17,6),'A law of motion has emerged from an optimization principle.','A law of motion has emerged from a stationary-action principle.','Stationarity need not be optimization')
