"""One-time review and correction of flagged prose beyond the openings."""
import json
from language_audit import ROOT, record, write
from lxml import etree as E
rows=json.loads((ROOT/'qa/additions/language-candidates.json').read_text('utf-8'))
edits={
0:r'Existence theorems justify limits, extrema, roots, and integrals under stated conditions. Their proofs depend on completeness of the real numbers.',
1:r'This appendix develops the proof arguments behind those results, including the roles of continuity, completeness, and closed intervals.',
2:r'Uniform continuity gives one interval-width bound that controls the oscillation throughout a closed interval. This is used to prove convergence of Riemann sums.',
5:r'When velocity changes little over a short interval, constant velocity gives a useful approximation to that interval\textquotesingle s displacement. Adding these approximations estimates the total displacement.',
6:r'For motion along a line, differentiating position gives velocity, and accumulating velocity over an interval gives the change in position. Explain why these operations are related and what additional starting information is needed to recover position.',
7:r'We first compute both quantities for constant velocity.',
8:r'For constant velocity, the slope calculation and the rectangular area calculation are exact.',
9:r'This formula requires constant velocity. For changing velocity, a single velocity value does not generally determine the total displacement.',
10:r'The slope and rectangle-area calculations here used constant velocity. Explain which calculation changes when velocity varies and why approximating over shorter intervals is useful.',
11:r'The car travels <m>80</m> miles forward and then <m>30</m> miles backward. Its odometer records total distance traveled:',
12:r'For piecewise-constant velocity, rectangles give exact displacement. If instead we have signed positions at equally spaced times, adding consecutive position changes recovers the final position from the initial one.',
13:r'Expand the sum as <m>(s_1-s_0)+(s_2-s_1)+\cdots+(s_n-s_{n-1})</m>. Each interior position appears once positively and once negatively, leaving <m>s_n-s_0</m>.',
14:r'Finite differences compute position changes, and summing consecutive differences recovers the total change. Explain this cancellation and why instantaneous velocity still requires a limiting process.',
15:r'Now suppose velocity is known and displacement is required.',
16:r'Explain the roles of derivatives, integrals, approximations, and differential equations in describing motion. Give one question answered by each.',
17:r'Both processes require a precise meaning of approximation error and nearness. The next chapters define distances, intervals, functions, and limits.',
18:r'What must be specified to make <m>h\to0</m> and convergence of approximating sums precise? Explain the input or index, the quantity being approximated, and the allowed error.',
21:r'Which gives more information about how the car moved: the velocity graph or the final displacement alone? Explain what the displacement omits.',
22:r'A total displacement does not determine the velocity history. Many different trips have the same signed displacement.',
23:r'The precise definition of a limit will require an input bound that meets every requested positive output tolerance:',
24:r'Here the error is exactly <m>|h|</m>, so the input and output tolerances can be the same. Other limits require a different relation between the two tolerances.',
25:r'In this average-velocity example, the error from <m>4</m> is <m>|h|</m>. Explain how to meet any positive output tolerance and why checking a finite table does not prove this for every tolerance.',
26:r'Rational numbers measure many distances, but they do not represent every point required by geometry and limiting processes. The next section explains why the real numbers are needed.',
27:r'The decimal approximations to <m>\sqrt2</m> give nested closed intervals whose lengths tend to zero. State what the Nested Interval Principle guarantees and explain why their common point is unavailable if only rational numbers are allowed.',
28:r'Tangent slopes, areas, bisection roots, and infinite decimals are defined through approximations. Explain how completeness supplies real limiting values when the appropriate convergence conditions hold.',
29:r'A graph can suggest a property of a function, but the plotted image alone does not prove it.',
30:r'A plotted graph depends on its window and sampling resolution. To establish a property for all inputs in a domain, use an argument that covers those inputs.',
31:r'A model represents a situation under stated assumptions. What four checks should be made, and why can an algebraically correct formula give an incorrect physical prediction outside its assumed range?',
32:r'Check assumptions, units, agreement with data, and the applicable range. Algebraic consistency alone does not establish agreement with the modeled situation.',
33:r'Doubling the side of a square quadruples its area. Explain the scaling relation in <m>y=Cx^p</m> and how it differs from constant additive change.',
34:r'Constant differences suggest an additive model, whereas constant ratios suggest a multiplicative model. Resource limits or changing rates may invalidate an exponential model beyond the observed data.',
35:r'When <m>h</m> is small, the numerator subtracts nearly equal numbers. Rounding can then affect the computed quotient substantially.',
36:r'The same formula can describe different quantities. Consider',
37:r'For <m>s(t)=t^2</m>, the average velocity from <m>2</m> to <m>2+h</m> is <m>4+h</m> for <m>h\ne0</m>. Explain how its error from <m>4</m> can be made smaller than any positive tolerance without evaluating the quotient at <m>h=0</m>.',
38:r'A limit concerns nearby values; the value assigned at the point is separate. Continuity requires those values to agree.',
39:r'The first situation is continuous at the point. The other two distinguish an existing nearby limit from the assigned function value.',
40:r'The error in a sum is bounded by the sum of the individual errors. Conversely, cancellation may make a sum converge even when its components have no limits.',
41:r'In a limit at <m>a</m>, only inputs <m>x\ne a</m> are relevant. Algebraic simplification may expose a limit, but the simplified expression must still be checked for unbounded or unequal one-sided behavior.',
42:r'When algebraic simplification is insufficient, inequalities can bound a function between two functions with the same limit.',
43:r'The next section treats unequal one-sided limits, unbounded outputs, and limits as the input tends to infinity.',
44:r'we usually mean approach from both sides. The two one-sided limits may differ.',
45:r'A left-hand limit uses inputs less than <m>a</m>; a right-hand limit uses inputs greater than <m>a</m>. A two-sided limit requires agreement between them.',
46:r'Infinity is not a real limiting value. The function may grow without bound positively on one side and negatively on the other, so each side must be described separately.',
49:r'A finite table checks only finitely many inputs. The limit definition requires an input bound for every positive output tolerance <m>\varepsilon</m>.',
50:r'The function may take the value <m>N</m> at several points. The theorem guarantees at least one such point, rather than uniqueness.',
51:r'The Intermediate Value Theorem guarantees a point with the specified intermediate value. It gives neither uniqueness nor a formula for that point.',
52:r'Continuity on a closed, bounded interval also ensures that the function attains its extrema.',
54:r'conclusion',
55:r'The Intermediate Value and Extreme Value Theorems require their stated continuity and interval conditions. The next section gives counterexamples when those conditions are removed.',
56:r'A line has constant slope. For a curved graph, the secant slope generally depends on both selected points.',
57:r'The derivative determines these intervals of increase and decrease:',
58:r'Continuity requires nearby function values to approach the value at the point.',
59:r'It does not imply that a finite tangent slope exists.',
60:r'This function is continuous everywhere. At zero, however, its left and right slopes differ:',
61:r'Continuity of the derivative is a stronger requirement than differentiability. The definition of a derivative does not by itself establish that <m>f\prime</m> is continuous.',
62:r'The function <m>x^2\sin(1/x)</m>, extended by zero at the origin, is differentiable there, but its nearby derivative values do not approach <m>f\prime(0)</m>. Explain the distinction between differentiability and continuity of the derivative.',
63:r'The rules in this chapter depend on how the function is formed:',
64:r'Explain how the differentiation rule depends on whether an expression is a sum, product, quotient, composition, or inverse. Why must this structure be identified before applying a formula?',
65:r'Use the exponential definitions to explain why <m>(\sinh x)\prime=\cosh x</m> and <m>(\cosh x)\prime=\sinh x</m>. Compare the signs with the derivatives of sine and cosine.',
66:r'A critical number is a candidate for an extremum, but need not be one.',
67:r'A number <m>c</m> in the domain is critical when <m>f\prime(c)=0</m> or the derivative is undefined. Explain why these points require checking and why either condition can occur without a local extremum.',
68:r'The theorem guarantees that <m>c</m> exists, even if it is difficult to calculate.',
69:r'Explain the roles of continuity on the closed interval, differentiability on its interior, and equal endpoint values in Rolle\textquotesingle s Theorem. Which hypotheses fail for a jump or a corner?',
70:r'If <m>s(t)</m> is measured in meters and <m>t</m> in seconds, the derivative units are',
71:r'The endpoint values agree, but the function has a corner. Rolle\textquotesingle s Theorem does not apply because differentiability fails at an interior point.',
72:r'The sign of the first derivative describes increase and decrease. The sign of the second derivative describes increase and decrease of the slope. Sign charts organize these properties across intervals.',
73:r'The next chapter applies derivatives to related rates, optimization, and mathematical models.',
75:r'Newton\textquotesingle s method uses a local linear approximation. Its convergence depends on the root, the derivative, and the starting value.',
76:r'Near a simple root, under suitable smoothness conditions, Newton\textquotesingle s error is approximately squared at each step. A multiple root requires a different convergence analysis.',
77:r'Explain how continuously compounded interest and Newton\textquotesingle s law of cooling both use a rate proportional to a current amount or difference from equilibrium. How does this relation determine the solution form?',
78:r'Where <m>y\ne0</m>, the exponential equation <m>y\prime=ky</m> specifies the constant relative rate <m>y\prime/y=k</m>. Explain why increasing values alone do not establish exponential growth.',
79:r'The model <m>P\prime=rP</m>, with <m>r&gt;0</m>, permits unbounded growth. Explain why it can approximate early population growth and why limited resources may invalidate it later.',
80:r'Exponential growth assumes a constant relative growth rate.',
81:r'Logistic growth assumes a fixed carrying capacity and a relative growth rate <m>r(1-P/K)</m>, approximately <m>r</m> when <m>P\ll K</m>.',
82:r'Check whether these assumptions describe the situation before using the model to predict its behavior.',
83:r'When <m>P\ll K</m>, the logistic model closely approximates exponential growth. Explain why early data may estimate <m>r</m> while providing little information about <m>K</m>.',
84:r'A more general problem varies an entire path.',
86:r'A stationary path has zero first-order change in travel time under the allowed small path variations. This condition does not by itself establish an absolute minimum.',
87:r'The reflection and refraction examples vary one crossing point. A functional instead takes an entire path as input and returns a number such as time or length. Explain how this changes the optimization problem.',
88:r'Choose quantities and constraints that represent the situation, and check the resulting model\textquotesingle s domain and assumptions.',
91:r'If the circular ends cost more, the minimizing radius decreases. Maintaining the fixed volume then requires a greater height.',
92:r'Exponential growth assumes a constant relative rate; logistic growth adds a fixed carrying capacity. Explain why these assumptions must be checked and why early data may not reveal the eventual capacity.',
93:r'A correct calculation does not validate the model\textquotesingle s assumptions. Early data resembling exponential growth may fail to reveal a later resource limit.',
94:r'The displacement is the sum of the three rectangle areas under the velocity graph.',
95:r'On sufficiently short intervals, slowly varying velocity is approximated by a constant. Summing the corresponding displacements estimates the total displacement.',
96:r'These rules follow from the corresponding rules for finite addition.',
97:r'This finite-sum identity anticipates the relation between differentiation and integration:',
98:r'Boundedness alone does not imply Riemann integrability. Continuous functions and bounded piecewise-continuous functions on a closed finite interval are integrable, but a bounded function can fail to have convergent Riemann sums.',
99:r'Linearity, interval splitting, and order properties of integrals follow by passing the corresponding finite-sum properties to limits.',
100:r'If upper and lower sums can be made arbitrarily close, their limiting values agree and determine a unique integral.',
101:r'The next chapter studies accumulation functions with a moving endpoint. For a continuous integrand, differentiating the accumulation recovers the integrand.',
102:r'The Fundamental Theorem will establish this relation between integration and differentiation.',
103:r'The theorem applies the rate-accumulation relation to motion.',
104:r'These antiderivative formulas follow from the corresponding derivative formulas.',
105:r'Explain why a variable factor cannot generally be pulled outside an integral and why <m>\int f(x)\,dx</m> is not generally <m>xf(x)</m>. How can differentiation check a proposed antiderivative?',
106:r'The inner and outer shell circumferences differ, so circumference times thickness gives an approximation to the annular cross-section. The resulting discrepancy tends to zero in the limiting sum.',
107:r'For constant force along the motion, work equals force times displacement. Explain why using only the final force is invalid for a varying force and how <m>\int F(x)\,dx</m> accounts for the variation.',
115:r'However, the function',
116:r'The length calculation uses the speed along the curve.',
117:r'When a tank\textquotesingle s shape has no convenient formula, measured cross-sectional data can be used to approximate the volume.',
118:r'The method uses this choice of factors:',
119:r'For <m>x=3\sin\theta</m>, derive <m>\sqrt{9-x^2}=3\cos\theta</m> on a branch where <m>\cos\theta\ge0</m>. Which identity and sign condition are needed?',
121:r'When exact integration is unavailable, numerical integration can approximate the value.',
122:r'A missed narrow peak, an improper endpoint, or subtractive rounding can invalidate an approximation. The algorithm must supply an applicable error bound or an explicitly qualified estimate.',
123:r'Simpson\textquotesingle s rule integrates quadratics exactly and, by symmetry, also integrates cubics exactly.',
124:r'Numerical integration and numerical differentiation replace limiting definitions by finite calculations. Both require analysis of truncation and rounding errors.',
125:r'Under the local convergence hypotheses, a simple root attracts Newton iterates started sufficiently close to it.',
126:r'Newton\textquotesingle s method can converge rapidly near a simple root yet fail from another starting value. Describe possible failures and explain which quantities should be monitored during iteration.',
127:r'Changing the initial value from <m>1</m> to <m>1.01</m> changes the subsequent iterates substantially.',
128:r'This example shows that a simple iteration rule can produce complicated behavior.',
129:r'Practical use of Newton\textquotesingle s method requires checks on convergence, residuals, and the computed iterates.',
130:r'Both examples illustrate the need to test a stopping criterion against a known reference.',
131:r'starting from <m>x_0=1</m>. What happens, and which feature of the iteration explains the result?',
132:r'Column <m>j</m> cancels the leading error of order <m>h^{2j}</m> from the preceding column. For fixed <m>j</m> and sufficient smoothness, its error is <m>O(h_k^{2j+2})</m> as the mesh shrinks. Finite-precision diagonal entries need not improve at every refinement.',
133:r'The next chapter changes the coordinate description of curves.',
134:r'Accuracy improves under the convergence hypotheses as the step shrinks. A large step can instead produce behavior inconsistent with the exact solution.',
135:r'Choose the step size using accuracy and stability considerations, and compare the numerical behavior with the direction field.',
136:r'For <m>y\prime=-4y</m>, a large Euler step can produce growing oscillations although the exact solution decays. Explain how the numerical update produces this discrepancy.',
137:r'Each Euler value is approximate, and the next slope is evaluated at that value. A large step may therefore lead to behavior inconsistent with the direction field.',
138:r'This statement identifies the numerical approximation and its step size.',
139:r'For <m>y\prime=y(1-y)</m>, dividing by <m>y(1-y)</m> excludes <m>y=0</m> and <m>y=1</m>. Explain why these are equilibrium solutions and how to check such excluded cases.',
140:r'Explain the roles of <m>rP</m> and <m>1-P/K</m> in the logistic equation. Why does the exponential model approximate early growth when <m>P\ll K</m> but fail to model a fixed carrying capacity?',
141:r'The threshold model has different equilibria and sign intervals from the logistic model.',
142:r'For <m>P\prime=rP(1-P/K)-h</m>, equilibria occur where logistic growth equals the harvest rate. Explain why the maximum of the growth term gives the largest sustainable constant harvest and what happens when <m>h</m> exceeds it.',
143:r'The preceding equation had a constant right side. An integrating factor also handles time-dependent <m>p(t)</m> and <m>q(t)</m>.',
144:r'Explain why a first-order linear solution combines an initial amount with an accumulated weighted input. What does <m>q(t)=0</m> mean in a mixing or deposit model?',
145:r'has sine and cosine solutions because their second derivatives are negative multiples of themselves.',
147:r'If the driving frequency <m>\gamma</m> is close to the natural frequency <m>\omega</m>, the denominator becomes small:',
148:r'Discarding these solutions would omit the model\textquotesingle s equilibria.',
149:r'When separation divides by an expression in <m>y</m>, its zeros are candidates for equilibrium solutions. Explain how to test them and why discarding them can omit important model behavior.',
150:r'A direction field can reveal numerical values inconsistent with the equation\textquotesingle s slopes, even when it cannot provide exact solution values.',
151:r'The coordinate formulas must be accompanied by a parameter interval to specify which part of the curve is traced and how often.',
152:r'Compare an ellipse centered at the origin with one whose focus is at the pole. Explain the usefulness of the focus-based polar equation for an orbit and which law describes the rate of traversal.',
153:r'Explain how complex multiplication represents scaling and rotation. Which power-series results are needed to justify Euler\textquotesingle s formula?',
154:r'An area formula that also records orientation is',
155:r'A central gravitational force has no tangential component. Explain why this implies conservation of <m>r^2\theta\prime</m> and which additional coordinate calculations are needed for a full orbit derivation.',
156:r'A full derivation requires the vector and coordinate tools developed in multivariable calculus.',
157:r'This optional connection will be developed later using infinite series.',
158:r'The domain contains integer indices, with no required values between consecutive indices.',
159:r'Convergence requires every sufficiently late term to meet each prescribed tolerance. Persistent separated oscillations and unbounded growth prevent convergence, but oscillations of shrinking amplitude may converge.',
160:r'The preceding examples have explicit formulas for their partial sums.',
161:r'For many series there is no useful explicit formula for <m>S_n</m>. Convergence tests determine whether the partial sums converge without such a formula.',
162:r'Its terms tend to zero, but its partial sums grow without bound.',
163:r'Geometric and telescoping partial sums simplify explicitly. For other series, a convergence test may be needed instead.',
164:r'The partial sums are unbounded.',
165:r'The first ten terms give limited decimal accuracy, but the remainder estimate specifies an interval containing the true sum.',
166:r'For nonnegative terms, convergence is equivalent to bounded partial sums. Comparison establishes boundedness, and a finite positive limit ratio makes the two positive tails comparable in both directions.',
167:r'The positive series diverges. The next section shows how alternating signs change its convergence behavior.',
168:r'This is a valid remainder bound, but it decreases slowly. Alternating convergence may require many terms for a small error.',
169:r'These convergence results will allow us to represent functions by series. For example,',
170:r'The form of a term helps determine an appropriate series test. Identify powers, factorials, ratios, or sign patterns before choosing the test.',
171:r'This interval contains the true sum by the remainder bound.',
172:r'When terms depend on <m>x</m>, additional questions arise:',
173:r'Explain why a power series centered at <m>a</m> converges at <m>a</m> and how <m>|x-a|</m> enters the ratio or root analysis.',
174:r'The radius determines the open interval of absolute convergence. Explain why the two endpoints must be tested separately and how equal radii can give different convergence intervals.',
175:r'Calculators evaluate <m>\sin x</m> using numerical algorithms, identities, approximations, and error control.',
176:r'The earlier discussion of polar form introduced the identity',
177:r'Power series with the same center can be added coefficient by coefficient on a common interval of absolute convergence. Explain why this does not automatically justify endpoint operations.',
178:r'For term-by-term definite integration, each term',
179:r'Next we derive series representations from the geometric series by substitution, differentiation, and integration. These methods produce logarithm and inverse-tangent series and help justify the identity',
180:r'At the justified endpoint, this inverse-tangent series gives the displayed representation of <m>\pi</m>.',
181:r'The factorial coefficients follow from repeated differentiation of powers:',
182:r'approximates the function near zero under the relevant remainder estimate. Matching derivatives at one point alone gives no accuracy bound far from that point.',
183:r'The integral remainder expresses the error as an integral involving a higher derivative. It provides another way to estimate that error.',
184:r'When Taylor expansions cancel in a limit, retain enough terms to identify the first nonzero difference and control the remainder. Explain how the first differing derivative determines that leading term.',
185:r'Taylor coefficients are derivatives at the expansion point. After cancellation, the first differing coefficient often determines the leading behavior in the limit.',
186:r'Uniform convergence on the integration interval justifies term-by-term integration. A bound on the remaining series then bounds the integral error.',
187:r'A power-series calculation needs a specified domain, convergence justification, and an applicable remainder estimate. Without these, formal manipulations may not establish an identity or an accurate approximation.',
188:r'means that the displayed series has the Fourier coefficients of <m>f</m>. It does not by itself establish convergence to <m>f(t)</m> at every point. That requires a separate convergence theorem.',
189:r'Fourier coefficients describe frequency components rather than derivatives at a point. Convergence of the resulting series requires separate conditions, particularly at discontinuities.',
190:r'<m>\int_a^b F\prime=F(b)-F(a)</m> requires the theorem\textquotesingle s differentiability and integrability conditions. A jump in <m>F</m> is not included in an ordinary derivative integral.',
191:r'An exact differential has the form <m>dF=F\prime(x)\,dx</m>. Explain why its integral reduces to a signed endpoint difference and how finding an antiderivative identifies such a differential.',
192:r'The Fundamental Theorem converts an integral of a derivative into endpoint values. Applied to a flux, this expresses the net boundary flow used in a conservation law:',
193:r'The Euler–Lagrange equation is a stationarity condition for a functional whose input is a path. Explain how integrating kinetic minus potential energy defines the action and why this optimization differs from varying a single real number.',
194:r'The cooling project asks for a solution, a parameter estimate, and a comparison with data. Explain why solving the equation does not establish the model\textquotesingle s accuracy and how mismatches should affect its assumptions.',
195:r'Additional computed digits do not establish accuracy. An applicable error bound quantifies the possible difference from the exact value.',
196:r'A numerical implementation needs both efficient evaluation and documented accuracy.',
}
for index,new in edits.items():
    row=rows[index];p=ROOT/row['file'];text=p.read_text('utf-8')
    after='<p>'+new.replace(r'\textquotesingle ',"'")+'</p>'
    if after in text:continue
    assert text.count(row['before'])==1,(index,row['file'])
    updated=text.replace(row['before'],after)
    E.fromstring(updated.encode())
    write(p,updated)
    record(p,row['id'],'Replace figurative or imprecise prose with the mathematical statement or question.',row['before'],after)
# Keep physical uses of depth and quiet, and ordinary problem statements such as
# a farmer wanting a field. Align repeated figure captions and descriptions.
phrases={
 'The same function can tell a different visual story in different windows.':'The viewing window can reveal or conceal features of the same function.',
 'Signed area preserves the net change, not the full story.':'Signed area gives the net change but does not determine the velocity at each time.',
 'even when the picture still looks calm':'even when a sampled graph appears to attain extrema',
 'what the honest check':'how differentiation checks',
}
for before,after in phrases.items():
    for p in (ROOT/'source').rglob('*'):
        if p.suffix not in {'.xml','.ptx'}:continue
        text=p.read_text('utf-8')
        if before not in text:continue
        root=E.fromstring(text.encode());xid=root.get('{http://www.w3.org/XML/1998/namespace}id')
        updated=text.replace(before,after);E.fromstring(updated.encode());write(p,updated)
        record(p,xid,'Align captions, descriptions, and questions with direct language.',before,after)
print('Body-language corrections:',len(edits))
