"""One-time opening-language corrections, chapters 5-8."""
from language_audit import opening, replace
edits={
'ch05-differentiation-rules-and-elementary-functions':r'<p>Differentiation rules let us find derivatives without evaluating the defining limit each time. This chapter develops rules for sums, products, quotients, compositions, implicit relations, and inverse functions, then applies them to the elementary functions. The appropriate rule depends on how the function is formed and where it is defined.</p>',
'sec-5-1-the-algebra-of-derivatives':r'<p>The derivative of a sum is the sum of the derivatives. Multiplication by a constant also passes through differentiation. We will prove these rules from the limit definition and use them to differentiate polynomials.</p>',
'sec-5-3-the-chain-rule':r'<p>In a composition <m>f(g(x))</m>, a change in <m>x</m> first changes <m>g(x)</m>, which then changes the output of <m>f</m>. The chain rule multiplies the derivative of the outer function, evaluated at <m>g(x)</m>, by the derivative of the inner function.</p>',
'sec-5-5-derivatives-of-trigonometric-functions':r'<p>Sine and cosine describe periodic behavior such as rotation and oscillation. Their derivatives are <m>(\sin x)\prime=\cos x</m> and <m>(\cos x)\prime=-\sin x</m> when angles are measured in radians. We will derive these formulas from limits and use them to differentiate the remaining trigonometric functions.</p>',
'sec-5-6-derivatives-of-exponential-and-logarithmic-functions':r'<p>The function <m>e^x</m> equals its own derivative. Consequently, exponentials describe quantities whose rates of change are proportional to their current values. We will derive exponential and logarithmic derivative formulas, with their domains stated explicitly.</p>',
'sec-5-7-inverse-functions-and-inverse-trigonometric-functions':r'<p>The derivative of an inverse function is the reciprocal of the original derivative at the corresponding input, provided that derivative is nonzero. We will justify this relation and apply it to inverse trigonometric functions. Choosing the inverse branch is necessary to specify both its domain and its derivative.</p>',
'sec-5-8-general-power-rule-and-hyperbolic-functions':r'<p>For <m>x&gt;0</m>, logarithms extend the power rule to every real exponent: <m>(x^r)\prime=rx^{r-1}</m>. This section proves that result, defines hyperbolic functions using exponentials, and develops their identities, inverses, and derivatives.</p>',
'sec-5-9-warning-examples':r'<p>Sums, products, quotients, compositions, and inverses require different differentiation rules. These examples show common errors in choosing a rule, applying the chain rule, and ignoring a function\textquotesingle s domain.</p>',
'sec-5-10-chapter-review-and-discovery-problems':r'<p>The review problems combine derivative rules with elementary functions, implicit relations, and inverse functions. Identify the structure of each expression before differentiating, and state the domain where the resulting formula applies.</p>',
'ch06-shape-extremes-and-the-mean-value-theorem':r'<p>Derivatives describe more than rates of change. Their signs determine intervals of increase and decrease, and second derivatives describe concavity. This chapter connects derivative information to extrema and graph shape, proves Rolle\textquotesingle s Theorem and the Mean Value Theorem, and applies these results to limits and estimates.</p>',
'sec-6-4-concavity-and-second-derivatives':r'<p>The first derivative describes whether a function increases or decreases. The second derivative describes how its slope changes. An increasing slope gives concave-up behavior, and a decreasing slope gives concave-down behavior. For motion, this distinction separates positive velocity from positive acceleration.</p>',
'sec-6-5-graph-sketching-with-calculus':r'<p>A graph sketch combines the domain, intercepts, limits, derivative signs, extrema, and concavity. We will organize this information to draw a graph consistent with the function\textquotesingle s formulas and limiting behavior.</p>',
'sec-6-7-warning-examples':r'<p>The conclusions of Rolle\textquotesingle s Theorem, the Mean Value Theorem, derivative tests for extrema, and l\textquotesingle Hospital\textquotesingle s Rule depend on their hypotheses. The examples below show failures caused by missing continuity, differentiability, endpoint conditions, or sign conditions.</p>',
'sec-6-8-chapter-review-and-discovery-problems':r'<p>These problems use derivatives to determine monotonicity, extrema, and concavity; sketch graphs; prove estimates with the Mean Value Theorem; and evaluate limits with l\textquotesingle Hospital\textquotesingle s Rule when its hypotheses hold.</p>',
'ch07-optimization-related-rates-and-models':r'<p>Applications of derivatives begin by expressing the relevant quantities as functions. We will build models for related rates, optimization, measurement error, growth, and least-time paths. In each case, interpret the result using the model\textquotesingle s domain, assumptions, and units.</p>',
'sec-7-1-related-rates':r'<p>When changing quantities satisfy an equation, differentiating that equation with respect to time relates their rates of change. For example, a balloon\textquotesingle s radius, surface area, and volume change together. The chain rule allows one known rate to determine another.</p>',
'sec-7-2-optimization-problems':r'<p>An optimization problem asks for a maximum or minimum under given constraints. First choose variables, determine their allowed values, and express the quantity to be optimized as a function. Then use derivatives and endpoint checks to compare all relevant candidates.</p>',
'sec-7-3-linear-approximation-in-applications':r'<p>A small measurement error in an input produces a corresponding change in the output. If <m>f</m> is differentiable near <m>a</m>, the tangent-line approximation gives</p><p><me>f(a+\Delta x)-f(a)\approx f\prime(a)\Delta x.</me></p><p>Thus the derivative estimates how sensitive the output is to an input change. We will apply this to measurement errors and explain the limitations of the approximation.</p>',
'sec-7-5-exponential-growth-and-decay':r'<p>When a quantity\textquotesingle s rate of change is proportional to its current amount, it satisfies <m>y\prime=ky</m>. Positive <m>k</m> gives exponential growth, and negative <m>k</m> gives exponential decay. Population models, radioactive decay, and continuously compounded interest provide examples.</p>',
'sec-7-6-logistic-growth-and-limited-resources':r'<p>The exponential model <m>P\prime=rP</m>, with <m>r&gt;0</m>, allows a positive population to grow without bound. To model limited resources, the logistic equation reduces the per-capita growth rate as the population approaches a carrying capacity.</p>',
'sec-7-7-light-time-and-extremal-principles':r'<p>Some optimization problems choose a path rather than a dimension or price. Reflection and refraction can be derived by minimizing travel time within a specified family of paths. We will write the travel time as a function of the crossing or reflection point and use its derivative to find the minimizing path.</p>',
'sec-7-8-warning-examples':r'<p>Derivative calculations must respect the model\textquotesingle s domain and constraints. A critical point may be infeasible or only a local optimum, and Newton\textquotesingle s method may fail to converge. These examples show how to check those possibilities.</p>',
'sec-7-9-chapter-review-and-applications':r'<p>These problems ask you to formulate models before applying derivatives. Specify the variables, constraints, and units; carry out the calculation; and interpret the result in the original situation.</p>',
'ch08-the-integral-as-accumulation':r'<p>An integral measures an accumulated quantity. Velocity determines displacement, power determines energy use, and density determines mass. We will approximate each total by dividing an interval into small pieces and adding their contributions, then define the definite integral as a limit of these sums.</p>',
'sec-8-4-the-definite-integral':r'<p>A Riemann sum approximates accumulation by adding function values multiplied by subinterval widths. The definite integral is their common limit, when it exists, as the largest subinterval width tends to zero. The limit must be independent of the partitions and sample points.</p>',
'sec-8-6-properties-of-the-integral':r'<p>The basic integral properties follow from Riemann sums and their limits. Integrals are linear, can be split at an intermediate endpoint, and preserve inequalities. Symmetry can also simplify calculations when the interval and integrand satisfy the required conditions.</p>',
'sec-8-7-existence-of-integrals':r'<p>A bounded function has a Riemann integral when its upper and lower sums can be made arbitrarily close. This section uses that criterion to establish integrability for continuous functions, monotone functions, and bounded functions with finitely many discontinuities. Boundedness alone is insufficient.</p>',
}
# Use ordinary apostrophes in prose; TeX commands belong only inside math.
for xid,new in edits.items():
    opening(xid,'Replace personification, slogans, or repeated setup with the operation, application, and hypotheses.',new.replace(r'\textquotesingle ',"'"))
replace('sec-8-2-area-under-a-graph','Remove a generic claim about usefulness.',
 'When velocity is nonnegative, distance traveled is the area under the velocity graph.  That observation is too useful to keep only for motion.',
 'The area calculation used for nonnegative velocity also applies to any nonnegative integrable function.')
print('Language corrections, chapters 5-8:',len(edits)+1)
