"""One-time opening-language corrections, chapters 1-4."""
from language_audit import opening, replace
edits={
'ch01-velocity-distance-and-the-first-shape-of-calculus':r'<p>Velocity describes how position changes with time. Accumulating velocity over a time interval gives the change in position. This chapter develops these two relationships using motion, slopes, areas, finite differences, and finite sums.</p>',
'sec-1-5-changing-velocity-and-the-need-for-limits':r'<p>When velocity is constant on each of finitely many time intervals, rectangles give the exact displacement. When velocity changes continuously, rectangles give approximations. We will refine those approximations by using shorter intervals. The same limiting process turns average velocity into instantaneous velocity.</p>',
'sec-1-6-a-first-map-of-the-book':r'<p>Slope measures a rate of change, and signed area measures an accumulated change. Finite differences and finite sums give discrete versions of these operations. Limits will connect them to derivatives and integrals.</p>',
'sec-1-7-discovery-problems-and-projects':r'<p>These problems connect velocity, position, slope, and signed area. Use graphs, tables, and motion examples to explain how a rate determines a change and how a change determines an average rate.</p>',
'ch02-numbers-functions-and-models':r'<p>Calculus uses functions to describe dependence and limits to describe approximation. Before defining limits, we need the real number line, intervals, distances, and error bounds. This chapter develops that language and uses it to describe graphs and mathematical models.</p>',
'sec-2-3-functions-as-assignments':r'<p>A function assigns one output to each allowed input. For example, a time can determine a position, a radius can determine an area, and a step size can determine an approximation error. We will specify both the assignment and the set of inputs on which it is defined.</p>',
'sec-2-5-combining-functions':r'<p>We can form new functions by adding, subtracting, multiplying, or dividing their outputs. Composition forms a new function by using the output of one function as the input of another. Each operation also imposes requirements on the domain.</p>',
'sec-2-6-a-catalog-of-essential-functions':r'<p>Several function families occur frequently in calculus. Lines describe constant rates, polynomials and rational functions describe algebraic relationships, trigonometric functions describe periodic behavior, and exponentials describe constant proportional growth or decay. Logarithms invert exponentials. This section reviews their formulas, domains, and graphs.</p>',
'sec-3-2-calculating-limits':r'<p>Limit laws allow us to calculate limits using arithmetic operations on simpler functions. We will also use algebraic simplification and inequalities when direct substitution is unavailable. Tables and graphs can suggest an answer; the calculation must justify it.</p>',
'sec-3-3-one-sided-limits-and-infinite-behavior':r'<p>A function can approach different values from the left and right, grow without bound near a point, or approach a limit as the input tends to infinity. These behaviors require separate definitions. A two-sided finite limit exists only when both one-sided limits exist and agree.</p>',
'sec-3-5-continuity':r'<p>A limit describes nearby function values and may exist even when the function is undefined at the point. Continuity at <m>a</m> requires the function value to exist and equal that limit: <m>\lim_{x\to a}f(x)=f(a)</m>.</p>',
'sec-3-6-two-theorems-about-continuous-functions':r'<p>A continuous function on a closed finite interval takes every value between its endpoint values and attains a maximum and a minimum. The Intermediate Value Theorem and the Extreme Value Theorem make these statements precise. Both depend on continuity; the extrema theorem also depends on the interval being closed and bounded.</p>',
'sec-3-7-warning-examples':r'<p>The Intermediate Value Theorem requires continuity on an interval. The Extreme Value Theorem requires continuity on a closed, bounded interval. The examples below show how their conclusions can fail when these conditions are removed. We will also distinguish a function value from its nearby limit.</p>',
'sec-3-9-chapter-review-and-discovery-problems':r'<p>This chapter defined limits and continuity, distinguished one-sided limits from two-sided limits, and treated unbounded behavior and sequence limits. The review problems ask you to calculate limits, check hypotheses, and apply the Intermediate Value and Extreme Value Theorems.</p>',
'ch04-the-derivative':r'<p>A derivative is the limit of average rates of change over intervals shrinking to a point:</p><p><me>f\prime(a)=\lim_{h\to0}\frac{f(a+h)-f(a)}{h}.</me></p><p>When this finite limit exists, it gives the instantaneous rate of change and the tangent slope at that point. This chapter defines the derivative, develops its first formulas, and explains its use in local approximation and motion.</p>',
'sec-4-2-instantaneous-rate-of-change':r'<p>Average velocity is displacement divided by elapsed time. Instantaneous velocity is the limit of this quotient as the nonzero time interval shrinks to zero. We take a limit; we do not evaluate the quotient with a zero denominator.</p>',
'sec-4-3-the-derivative-as-a-function':r'<p>At each input where a function is differentiable, its derivative gives the tangent slope. Collecting these values defines a new function, <m>f\prime</m>. For <m>f(x)=x^2</m>, the derivative function is <m>f\prime(x)=2x</m>, so in particular <m>f\prime(2)=4</m>.</p>',
'sec-4-4-local-linear-approximation':r'<p>If <m>f</m> is differentiable at <m>a</m>, the tangent line gives the local approximation <m>f(x)\approx f(a)+f\prime(a)(x-a)</m>. We will describe how the approximation error behaves as <m>x\to a</m> and use it to estimate changes in function values.</p>',
'sec-4-5-differentiability-and-continuity':r'<p>Differentiability at <m>a</m> gives</p><p><me>f(a+h)=f(a)+f\prime(a)h+E(h),\qquad E(h)/h\to0.</me></p><p>The terms <m>f\prime(a)h</m> and <m>E(h)</m> both tend to zero. Hence <m>f(a+h)\to f(a)</m>: differentiability implies continuity. The converse fails, as the examples below show.</p>',
'sec-4-7-motion-revisited':r'<p>For a position function <m>s(t)</m>, velocity is <m>v(t)=s\prime(t)</m> and acceleration is <m>a(t)=v\prime(t)</m>, wherever these derivatives exist. We will use their signs and units to describe direction, speed, and changes in speed.</p>',
'sec-4-8-warning-examples':r'<p>A continuous function need not be differentiable, and a derivative need not be continuous. These examples distinguish those properties and show why a sampled graph cannot establish differentiability.</p>',
}
for xid,new in edits.items():opening(xid,'Replace vague metaphors, repetition, or introductory filler with the section concept and conditions.',new)
replace('sec-1-2-constant-velocity-where-slope-and-area-first-meet','Replace a backward-looking setup with the assumption being studied.',
 'The dashboard gave us two questions.  Constant velocity is the first case where both questions can be answered without any limiting process.',
 'With constant velocity, displacement is velocity multiplied by elapsed time. The position graph has constant slope, and the velocity graph gives a rectangle whose area is the displacement.')
replace('sec-1-3-forward-backward-and-signed-motion','Remove the dashboard-story metaphor.',
 'Constant velocity gave us the first picture of calculus: slope on one graph and area on another.  But we quietly assumed that the car only moved forward.  The moment a car can reverse, the dashboard story needs one more idea.',
 'When motion can reverse direction, speed alone does not describe it. Signed velocity records both how fast an object moves and which direction it moves.')
replace('sec-1-4-calculus-without-limits-finite-differences-and-finite-sums','Replace an arithmetic-core slogan with the operation.',
 'Signed motion taught us to add changes with their signs.  Now we strip the story down to its arithmetic core.',
 'A finite difference measures the change between two recorded positions. Adding successive signed changes gives the total displacement.')
replace('sec-2-2-completeness-and-the-idea-of-no-gaps','Replace a vague promise with the completeness question.',
 'The last section used the real line as if every point on it had a number.  That is a stronger promise than it may first appear.',
 'Rational numbers do not supply every point needed for limits. Completeness is the property of the real numbers that ensures bounded increasing approximations have a real limit.')
replace('sec-2-7-models-before-calculus','Remove a metaphor while retaining the definition and checks.',
 'A model is not the same thing as reality.  It is a mathematical story about reality.  A good model respects units, captures the main pattern, and makes predictions we can test.',
 'A mathematical model represents selected features of a situation under stated assumptions. Its units should be consistent, and its predictions should be checked against data.')
replace('sec-2-8-technology-and-graphs','Replace a partnership slogan with concrete limitations.',
 'The right attitude is not distrust.  It is partnership.',
 'Check features suggested by a plotted graph using the formula, the sampling resolution, and the chosen viewing window.')
print('Language corrections, chapters 1-4:',len(edits)+6)
