"""One-time opening-language corrections, chapters 9-12."""
from language_audit import opening, replace
edits={
'ch09-the-fundamental-theorem-of-calculus':r'<p>For a continuous function <m>f</m>, the accumulation function <m>A(x)=\int_a^x f(t)\,dt</m> has derivative <m>A\prime(x)=f(x)</m>. Conversely, an antiderivative <m>F</m> evaluates a definite integral by <m>\int_a^b f=F(b)-F(a)</m>. This chapter proves these two parts of the Fundamental Theorem and develops antiderivatives and substitution.</p>',
'sec-9-3-fundamental-theorem-part-ii':r'<p>The first part of the Fundamental Theorem produces an antiderivative by integration. The second part evaluates an integral using any antiderivative: if <m>F\prime=f</m> on the interval and <m>f</m> is continuous, then <m>\int_a^b f(x)\,dx=F(b)-F(a)</m>. This avoids calculating a limit of Riemann sums separately for every integral.</p>',
'sec-9-4-indefinite-integrals':r'<p>A definite integral gives a number. An indefinite integral denotes the family of antiderivatives of a function. On an interval, all antiderivatives of the same function differ by a constant. We will use this fact to write and check indefinite-integral formulas.</p>',
'sec-9-5-differential-notation-and-oriented-length':r'<p>Substitution follows from the chain rule. When <m>x=g(u)</m>, the expression <m>dx=g\prime(u)\,du</m> records the factor that converts the integrand to the new variable:</p><p><me>f(x)\,dx=f(g(u))g\prime(u)\,du.</me></p><p>The sign of <m>g\prime</m> records orientation. In a definite integral, the endpoints must also be expressed in the new variable.</p>',
'sec-9-6-warning-examples':r'<p>These examples examine four common errors: applying the Fundamental Theorem across a discontinuity, retaining old endpoints after substitution, treating an integral as a product, and confusing a signed integral with ordinary area.</p>',
'sec-9-7-chapter-review-and-discovery-problems':r'<p>The Fundamental Theorem relates differentiation to integration. For continuous <m>f</m>, differentiating <m>\int_a^x f(t)\,dt</m> gives <m>f(x)</m>; integrating a continuous derivative gives <m>F(b)-F(a)</m>. The review problems apply these results to accumulation functions, antiderivatives, and substitutions, with attention to domains and hypotheses.</p>',
'ch10-what-integrals-measure':r'<p>To set up an integral for a total quantity, identify the contribution of a small piece and add those contributions over the relevant interval. For volume, the contribution is cross-sectional area times thickness. For mass, it is density times length or area. This chapter develops that approach for geometric quantities, work, fluid force, averages, and probability, with units used to check each formula.</p>',
'sec-10-1-area-between-curves':r'<p>The area between two curves can be computed by adding thin strips. For vertical strips, the height is the upper function minus the lower function; for horizontal strips, the width is the right boundary minus the left boundary. Split the region where the order of the boundaries changes.</p>',
'sec-10-3-cylindrical-shells':r'<p>Rotating a strip parallel to the axis produces a thin cylindrical shell. Its volume is approximately circumference times height times thickness:</p><p><me>\text{shell volume}\approx2\pi(\text{radius})(\text{height})(\text{thickness}).</me></p><p>Integrating these contributions gives the shell method. The radius is the distance from the strip to the rotation axis.</p>',
'sec-10-5-work-and-energy':r'<p>Work measures energy transferred by a force through displacement. For a force along a line, a small displacement contributes approximately <m>F(x)\,\Delta x</m>. Integrating the signed force over the displacement gives the total work.</p>',
'sec-10-6-hydrostatic-force':r'<p>Fluid pressure increases with depth. To compute the force on a submerged surface, divide it into strips narrow enough that the pressure is nearly constant on each strip. Multiply the pressure by the strip area and integrate.</p>',
'sec-10-7-average-value-and-probability':r'<p>The average value of an integrable function on <m>[a,b]</m>, with <m>a&lt;b</m>, is its integral divided by the interval length. Weighted averages replace equal weighting by a density or weight function. Probability densities provide an important application of this distinction.</p>',
'sec-10-8-arc-length-and-surface-area-of-revolution':r'<p>Approximate a smooth curve by short line segments to compute its length. For a graph, the Pythagorean theorem gives the length factor <m>\sqrt{1+(dy/dx)^2}</m>. Rotating a short segment about an axis gives a surface-area contribution equal to circumference times segment length.</p>',
'sec-10-9-chapter-review-and-applications':r'<p>The review problems ask you to choose and integrate the contributions that give area, volume, mass, work, fluid force, averages, probability, arc length, and surface area. State the boundaries, check the units, and explain why the chosen integral represents the requested quantity.</p>',
'ch11-techniques-of-integration':r'<p>Different integrands require different methods. Substitution reverses the chain rule, integration by parts reverses the product rule, and identities or partial fractions simplify the expression before integration. We will also treat improper integrals as limits and distinguish convergence from the availability of an elementary antiderivative.</p>',
'sec-11-1-integration-by-parts':r'<p>Integration by parts follows from the product rule. It rewrites the integral of one product in terms of another, which may be easier to evaluate. Integrands such as <m>xe^x</m>, <m>x\cos x</m>, and <m>x^2\ln x</m> are typical applications.</p>',
'sec-11-5-strategy-for-integration':r'<p>Before choosing a method, simplify the integrand and look for a derivative factor, a product suitable for integration by parts, a useful identity, or a rational expression suitable for partial fractions. No single technique works for every integral. We will compare these choices on examples.</p>',
'sec-11-6-computer-algebra-systems-and-integral-tables':r'<p>Integral tables and computer algebra systems can suggest antiderivatives and simplify expressions. Check a proposed answer by differentiating it on the relevant domain. Pay particular attention to absolute values, branch choices, singularities, and assumptions that may be implicit in the output.</p>',
'sec-11-7-improper-integrals':r'<p>An integral over an infinite interval, or with an unbounded integrand near an endpoint or interior point, is defined using limits of integrals over finite nonsingular intervals. It converges when every required limit is finite. This section develops comparison tests and distinguishes absolute convergence from convergence caused by cancellation.</p>',
'sec-11-8-warning-examples':r'<p>For an improper integral, apply the Fundamental Theorem only on finite nonsingular intervals, then take the required limits. If there is an interior singularity or two infinite tails, treat each piece separately. The examples below show errors caused by skipping these steps.</p>',
'sec-11-9-chapter-review-and-discovery-problems':r'<p>These problems combine substitution, integration by parts, trigonometric and hyperbolic identities, partial fractions, and improper-integral tests. Explain the choice of method, check antiderivatives by differentiation, and justify any improper limits.</p>',
'ch12-numerical-integration-error-and-computation':r'<p>Numerical methods approximate integrals, derivatives, and roots when exact calculations are unavailable or inconvenient. We will derive the methods, state the smoothness conditions behind their error estimates, and examine how step size, stopping rules, and rounding affect the results.</p>',
'sec-12-1-why-approximate-integrals':r'<p>Numerical integration approximates a definite integral using sampled function values. It is useful when the function is given by data, has no accessible antiderivative, or requires a numerical answer. An approximation should be accompanied by an error bound or a clearly identified error estimate.</p>',
'sec-12-2-midpoint-and-trapezoidal-rules':r'<p>The midpoint rule uses a rectangle whose height is the function value at the midpoint. The trapezoidal rule joins the endpoint values by a line. Applying either rule on many subintervals approximates an integral. We will derive their error bounds under bounds on the second derivative.</p>',
'sec-12-3-simpson-s-rule':r'<p>Simpson\textquotesingle s rule integrates a quadratic interpolant through two endpoints and their midpoint. Its composite form uses an even number of equal subintervals. When the fourth derivative is bounded, the error is bounded by a constant times the fourth power of the mesh width.</p>',
'sec-12-4-numerical-differentiation':r'<p>Finite differences estimate derivatives from sampled values. Their truncation error decreases as the step shrinks under suitable smoothness assumptions, but subtracting nearby values and dividing by a small step can amplify measurement and rounding errors. We will examine this tradeoff.</p>',
'sec-12-5-newton-s-method-revisited':r'<p>Newton\textquotesingle s iteration for a root of <m>f</m> is</p><p><me>x_{n+1}=x_n-\frac{f(x_n)}{f\prime(x_n)},</me></p><p>when the denominator is nonzero. This section examines convergence near a root, error and residual estimates, multiple roots, and stopping rules. It also shows how a poor starting value or a small derivative can cause failure.</p>',
'sec-12-6-computing-experiments':r'<p>These experiments compare numerical rules on functions with known reference values. Vary the step size, record the errors, and explain how smoothness and rounding affect the observed accuracy. Verify the implementation on simple exact cases before using it on harder examples.</p>',
'sec-12-7-chapter-review-and-discovery-problems':r'<p>These problems compare numerical integration rules, finite-difference derivatives, and Newton iteration. For each approximation, identify the exact quantity, the algorithm, its hypotheses, and the available error evidence.</p>',
'sec-additional-richardson-romberg':r'<p>When an approximation has a known leading error term in the step size, two mesh sizes can be combined to cancel that term. This optional section derives Richardson extrapolation and applies it repeatedly to the trapezoidal rule to obtain Romberg integration. The improved orders require the stated error expansion and sufficient smoothness.</p>',
}
for xid,new in edits.items():opening(xid,'Replace generic transitions, metaphors, or promotional claims with the method and its mathematical conditions.',new.replace(r'\textquotesingle ',"'"))
replace('sec-11-3-trigonometric-substitution','Remove the magic and hidden-geometry metaphor.',
 'The square root does not vanish by magic.  It vanishes because a right triangle or a circle was hidden inside it.',
 'The identities simplify the square root after a branch has been chosen to give the correct sign.')
print('Language corrections, chapters 9-12:',len(edits)+1)
